name: Build and push

env:
  REGISTRY_LOGIN_SERVER: tastycook.azurecr.io

on:
  workflow_call:
    inputs:
      service:
        required: true
        type: string
    secrets:
      REGISTRY_USERNAME:
        required: true
      REGISTRY_PASSWORD:
        required: true
      CLOUD_PAT:
        required: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - service: ${{ inputs.service }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Prepare variables
        id: prep
        run: |
          SERVICE_NAME=$(grep -oP '(?<=IMG \?= ${{ env.REGISTRY_LOGIN_SERVER }}/)[^\s]+' ${{ matrix.service }}/Makefile)
          TAG=$(git rev-parse --short HEAD)
          echo ::set-output name=service_name::$SERVICE_NAME
          echo ::set-output name=tag::$TAG

      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Update TAG in Makefile
        run: |
          sed -i "s|TAG ?=.*|TAG ?= ${{ steps.prep.outputs.tag }}|" ${{ matrix.service }}/Makefile
          git config user.name 'GitHub Actions'
          git config user.email 'actions@github.com'
          git add -A
          git commit -m "Update ${{ steps.prep.outputs.service_name }} image tag to ${{ steps.prep.outputs.tag }}"
          git fetch origin
          git config pull.rebase false
          git pull
          git push

      - name: Build and push Docker image
        run: |
          cd ${{ matrix.service }}
          make docker-build
          make docker-push

      - name: Checkout cloud repo
        uses: actions/checkout@v2
        with:
          repository: TastyCook/TastyCookCloud
          token: ${{ secrets.CLOUD_PAT }}
          path: .

      - name: Update tags in cloud repo
        run: |
          find . -type f -name '*.yaml' -print0 | xargs -0 sed -i "s|image: ${{ env.REGISTRY_LOGIN_SERVER }}/${{ steps.prep.outputs.service_name }}:[^ \"]*|image: ${{ env.REGISTRY_LOGIN_SERVER }}/${{ steps.prep.outputs.service_name }}:${{ steps.prep.outputs.tag }}|g"
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add -A
          git commit -m "Update ${{ steps.prep.outputs.service_name }} image tag to ${{ steps.prep.outputs.tag }}"
          git push
