name: ProductsAPI build and push

on:
  push:
    branches:
      - main
    paths:
      - 'TastyCook.ProductsAPI/**'

jobs:
  build:
    uses: ./.github/workflows/build-and-push.yaml
    with:
      service: TastyCook.ProductsAPI
      dotnet-version: "7.0"
    secrets:
      REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
      REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
      CLOUD_PAT: ${{ secrets.CLOUD_PAT }}
